"""
Django settings for velocity project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG')

ALLOWED_HOSTS = ['*','13.201.101.168','localhost','127.0.0.1','velocitywebtechsolution.com','www.velocitywebtechsolution.com']


CORS_ORIGIN_WHITELIST = [
   'http://localhost',
   'http://127.0.0.1',
   'http://0.0.0.0',
]


USE_X_FORWARDED_HOST = True


CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # ✅ Allows Next.js local development
    "http://13.201.101.168",
    "http://velocitywebtechsolution.com",
    "http://www.velocitywebtechsolution.com",
    "https://velocitywebtechsolution.com",
    "https://www.velocitywebtechsolution.com",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]



CORS_ALLOW_ALL_ORIGINS = True  # Allows all origins (for testing)
CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_HTTPONLY = False  # Make sure it's accessible
CSRF_COOKIE_NAME = "csrftoken"
SESSION_COOKIE_HTTPONLY = True  # Recommended for security
XS_SHARING_ALLOWED_METHODS = ['POST', 'GET', 'OPTIONS', 'PUT', 'DELETE']
CORS_ALLOW_METHODS = [
   'GET',
   'POST',
   'PUT',
   'PATCH',
   'DELETE',
   'OPTIONS'
]
CORS_ALLOW_HEADERS = [
   'content-type',
   'authorization',
   'X-CSRFToken'
]
# 3.
CSRF_TRUSTED_ORIGINS = [
   "http://13.201.101.168",
   "http://localhost:3000",
   "http://127.0.0.1:3000",
   "http://127.0.0.1:8000",
   "http://localhost:8000",
   "http://velocitywebtechsolution.com",
   "http://www.velocitywebtechsolution.com",
   "https://velocitywebtechsolution.com",
   "https://www.velocitywebtechsolution.com",
]


# Auto logout settings...
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'oauth2_provider',
    'corsheaders',
    'rest_framework',
    'accounts',
    'velocity_webtech',

]

JAZZMIN_SETTINGS = {
    "site_title": "Velocity Webtech Admin",
    "site_header": "Velocity Webtech",
    "site_brand": "Velocity Admin",
    "welcome_sign": "Welcome to Velocity Webtech administration",
    "copyright": "Velocity Webtech",
    "search_model": ["auth.User"],
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["oauth2_provider", "auth"],
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {
            "name": "Support",
            "url": "mailto:subhankar.rc@velocitywebtechsolution.com",
            "new_window": True,
        },
        {"model": "auth.User"},
        {"app": "oauth2_provider"},
    ],
    "custom_css": "accounts/css/jazzmin-admin.css",
    "show_ui_builder": False,
    "show_theme_chooser": False,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "oauth2_provider": "fas fa-shield-alt",
        "oauth2_provider.Application": "fas fa-plug",
        "oauth2_provider.AccessToken": "fas fa-key",
        "oauth2_provider.RefreshToken": "fas fa-sync-alt",
        "oauth2_provider.Grant": "fas fa-ticket-alt",
        "oauth2_provider.IDToken": "fas fa-id-card",
    },
}

JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    "default_theme_mode": "light",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_small_text": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_flat_style": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',

]

AUTHENTICATION_BACKENDS = (
   'django.contrib.auth.backends.ModelBackend',  # For standard authentication
   'oauth2_provider.backends.OAuth2Backend',     # For OAuth2 authentication
)


OAUTH2_PROVIDER = {
   'ACCESS_TOKEN_EXPIRE_SECONDS': 36000,
   'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.OAuthLibCore',
   'OAUTH2_PROVIDER_APPLICATION_MODEL': 'accounts.CustomApplication',  # If you have a custom model
   'OAUTH2_PROVIDER_GRANT_TYPES': ['password', 'authorization_code', 'client_credentials', 'refresh_token'],
}



ROOT_URLCONF = 'velocity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'velocity.wsgi.application'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': os.getenv('ENGINE'),
        'NAME': os.getenv('NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('PASSWORD'),
        'HOST': os.getenv('HOST'),
        'PORT': os.getenv('PORT')
    },

}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/


STATIC_URL = '/api/static/'
CORS_ORIGIN_ALLOW=True


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

BUSINESS_EMAIL = "subhankar.rc@velocitywebtechsolution.com"
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = (os.getenv("EMAIL_HOST_USER") or BUSINESS_EMAIL).strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = (os.getenv("DEFAULT_FROM_EMAIL") or EMAIL_HOST_USER).strip()
CONTACT_RECEIVER_EMAIL = (
    os.getenv("CONTACT_RECEIVER_EMAIL") or EMAIL_HOST_USER
).strip()
