# Generated by Django 6.1 on 2026-09-03 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velocity_webtech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryEmailReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('contact_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_replies', to='velocity_webtech.contactsubmission')),
            ],
            options={
                'verbose_name': 'Enquiry email reply',
                'verbose_name_plural': 'Enquiry email replies',
                'ordering': ['-sent_at'],
            },
        ),
    ]
