import {
  BadgeCheck,
  Cloud,
  Code2,
  Globe2,
  Headphones,
  Layers3,
  Lock,
  MonitorCog,
  Server,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
} from "lucide-react";

export const pricingSections = [
  {
    id: "website-development",
    path: "/website-development-services-pricing/",
    number: "01",
    title: "Website Development",
    eyebrow: "Professional websites",
    text: "Responsive, fast-loading business websites with clean layouts, contact forms, domain guidance, hosting setup, and SEO-friendly structure.",
    icon: Globe2,
    tone: "blue",
    items: [
      ["Starter Website", "Starting at Rs. 9,999"],
      ["Business Website", "Starting at Rs. 19,999"],
      ["E-commerce Website", "Starting at Rs. 29,999"],
      ["School Website", "Starting at Rs. 14,999"],
      ["Custom Website", "Starting at Rs. 24,999"],
    ],
    deliverables: [
      "Responsive desktop and mobile pages",
      "Contact form and lead capture setup",
      "SEO-ready page structure",
      "Domain, hosting and launch guidance",
    ],
  },
  {
    id: "mobile-app-development",
    path: "/mobile-app-development-services-pricing/",
    number: "02",
    title: "Mobile App Development",
    eyebrow: "Android and iOS apps",
    text: "User-friendly Android and iOS apps with smooth performance, scalable architecture, admin panel integration, and business-ready flows.",
    icon: Smartphone,
    tone: "green",
    items: [
      ["Basic Android App", "Starting at Rs. 29,999"],
      ["Android + iOS App", "Starting at Rs. 59,999"],
      ["Advanced Business App", "Starting at Rs. 79,999"],
      ["E-commerce App", "Starting at Rs. 89,999"],
      ["Custom App Solution", "Starting at Rs. 1,49,999"],
    ],
    deliverables: [
      "Clean mobile UI and app navigation",
      "API and admin panel integration",
      "Authentication and business workflows",
      "Release-ready scalable app structure",
    ],
  },
  {
    id: "custom-software-development",
    path: "/custom-software-development-services-pricing/",
    number: "03",
    title: "Custom Software Development",
    eyebrow: "Business automation",
    text: "Tailor-made software for automation, management, reporting, inventory, billing, customer records, and workflow improvement.",
    icon: MonitorCog,
    tone: "violet",
    items: [
      ["Business Software", "Starting at Rs. 49,999"],
      ["CRM / ERP Solution", "Starting at Rs. 79,999"],
      ["School Management Software", "Starting at Rs. 39,999"],
      ["Inventory / Billing Software", "Starting at Rs. 34,999"],
      ["Custom Solution", "Starting at Rs. 69,999"],
    ],
    deliverables: [
      "Role-based dashboards and workflows",
      "Reports, records and data management",
      "Automation for daily operations",
      "Secure database-backed application",
    ],
  },
  {
    id: "e-commerce-development",
    path: "/e-commerce-development-services-pricing/",
    number: "04",
    title: "E-commerce Development",
    eyebrow: "Online selling systems",
    text: "Conversion-focused online stores with product catalogues, checkout flows, secure payments, order management, and admin control.",
    icon: ShoppingCart,
    tone: "orange",
    items: [
      ["Starter Online Store", "Starting at Rs. 29,999"],
      ["Business E-commerce", "Starting at Rs. 49,999"],
      ["Payment Gateway Setup", "Starting at Rs. 9,999"],
      ["Order Management Panel", "Starting at Rs. 19,999"],
      ["Custom Marketplace", "Starting at Rs. 89,999"],
    ],
    deliverables: [
      "Product catalogue and cart workflow",
      "Checkout and secure payment setup",
      "Order management admin panel",
      "Customer-friendly shopping experience",
    ],
  },
  {
    id: "ui-ux-design",
    path: "/ui-ux-design-services-pricing/",
    number: "05",
    title: "UI/UX Design",
    eyebrow: "Modern product design",
    text: "Modern, attractive, and user-focused designs for websites, apps, dashboards, prototypes, and product screens.",
    icon: Layers3,
    tone: "cyan",
    items: [
      ["Landing Page Design", "Starting at Rs. 4,999"],
      ["Website UI Design", "Starting at Rs. 12,999"],
      ["Mobile App UI Design", "Starting at Rs. 19,999"],
      ["Dashboard UI Design", "Starting at Rs. 14,999"],
      ["Clickable Prototype", "Starting at Rs. 9,999"],
    ],
    deliverables: [
      "Clean layout and visual hierarchy",
      "User flows and screen planning",
      "Responsive web and mobile designs",
      "Prototype-ready design direction",
    ],
  },
  {
    id: "api-backend-development",
    path: "/api-backend-development-services-pricing/",
    number: "06",
    title: "API & Backend Development",
    eyebrow: "Secure backend systems",
    text: "Secure APIs, databases, authentication, admin workflows, integrations, and backend systems built for long-term scaling.",
    icon: Server,
    tone: "indigo",
    items: [
      ["REST API Development", "Starting at Rs. 19,999"],
      ["Database Architecture", "Starting at Rs. 14,999"],
      ["Admin Panel Backend", "Starting at Rs. 24,999"],
      ["Third-party Integration", "Starting at Rs. 9,999"],
      ["Custom Backend System", "Starting at Rs. 49,999"],
    ],
    deliverables: [
      "REST APIs and backend logic",
      "Database schema and data security",
      "Admin panels and permissions",
      "Third-party service integrations",
    ],
  },
  {
    id: "cloud-deployment-services",
    path: "/cloud-deployment-services-pricing/",
    number: "07",
    title: "Cloud & Deployment Services",
    eyebrow: "Launch and support",
    text: "Deployment, hosting, maintenance, cloud setup, domain support, performance optimization, and reliable post-launch guidance.",
    icon: Cloud,
    tone: "sky",
    items: [
      ["Website Maintenance", "Starting at Rs. 2,999 / month"],
      ["POS / Billing Software", "Starting at Rs. 24,999"],
      ["Software Support & Upgrades", "Starting at Rs. 44,999"],
      ["Domain & Hosting Support", "Starting at Rs. 1,499 / year"],
      ["Digital Consultation", "Starting at Rs. 1,999"],
    ],
    deliverables: [
      "Hosting and deployment setup",
      "Domain and DNS guidance",
      "Maintenance and upgrade support",
      "Performance and reliability checks",
    ],
  },
];

export const pricingHighlights = [
  {
    title: "Modern Design",
    text: "Attractive, responsive and user-focused designs.",
    icon: BadgeCheck,
  },
  {
    title: "Secure Solutions",
    text: "Robust security, data protection and privacy care.",
    icon: Lock,
  },
  {
    title: "Affordable Pricing",
    text: "Transparent pricing with the right value for money.",
    icon: ShieldCheck,
  },
  {
    title: "Expert Support",
    text: "Dedicated support and guidance at every step.",
    icon: Headphones,
  },
];

export function getPricingSection(id) {
  return pricingSections.find((section) => section.id === id);
}
