import {
  BadgeCheck,
  BookOpenCheck,
  BriefcaseBusiness,
  Cloud,
  Database,
  Globe2,
  Headphones,
  Layers3,
  Lock,
  MonitorCog,
  Server,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
} from "lucide-react";

export const pricingSections = [
  {
    id: "website-development",
    path: "/website-development-services/",
    number: "01",
    title: "Website Development",
    eyebrow: "Professional websites",
    text: "Build a professional, fast, responsive, and SEO-friendly website that helps your business create a strong online presence and reach more customers.",
    icon: Globe2,
    tone: "blue",
    intro:
      "At Velocity Webtech Solution, we design and develop modern websites tailored to your business goals, brand identity, and customer needs. Whether you need a simple business website, portfolio, school website, e-commerce platform, or a fully customized web application, we provide scalable and user-friendly solutions.",
    items: [
      ["Starter Website", "Starting at Rs. 4,999"],
      ["Business Website", "Starting at Rs. 19,999"],
      ["E-commerce Website", "Starting at Rs. 29,999"],
      ["School Website", "Starting at Rs. 14,999"],
      ["Custom Website", "Starting at Rs. 24,999"],
    ],
    deliverables: [
      "Responsive design for mobile, tablet and desktop",
      "Fast-loading pages with SEO-friendly structure",
      "Contact and enquiry forms",
      "Google Maps and social media integration",
      "Basic security setup",
      "Domain and hosting guidance",
      "Payment gateway integration where required",
      "Admin panel or CMS integration",
      "Ongoing maintenance and technical support",
    ],
    audience:
      "We work with startups, shops, schools, professionals, service providers, local businesses, and growing companies to create websites that are attractive, reliable, easy to use, and designed to generate enquiries and business opportunities.",
    whyChoose: [
      "Modern design",
      "Mobile responsiveness",
      "Clean development",
      "Transparent pricing",
      "Scalable solutions",
      "Secure implementation",
      "Dedicated support after launch",
    ],
    startingPrice:
      "Starting from Rs. 4,999 depending on the type of website, number of pages, features, integrations, and customization required.",
    cta: "Ready to Build Your Website? Contact Velocity Webtech Solution Today.",
    hidePricingDetails: true,
  },
  {
    id: "mobile-app-development",
    path: "/mobile-app-development-services/",
    number: "03",
    title: "Mobile App Development",
    eyebrow: "Android and iOS apps",
    text: "Build modern, fast, and user-friendly mobile applications for Android and iOS that help your business connect with customers anytime, anywhere.",
    icon: Smartphone,
    tone: "green",
    storyTitle: "Mobile apps built for smooth customer experiences.",
    intro:
      "At Velocity Webtech Solution, we develop mobile apps that are designed around your business requirements, target users, and long-term growth. Whether you need a simple business app, customer service app, booking app, e-commerce app, educational app, or a fully customized mobile solution, we can build a scalable application with a smooth user experience.",
    items: [
      ["Basic Android App", "Starting at Rs. 19,999"],
      ["Android + iOS App", "Starting at Rs. 59,999"],
      ["Advanced Business App", "Starting at Rs. 79,999"],
      ["E-commerce App", "Starting at Rs. 89,999"],
      ["Custom App Solution", "Starting at Rs. 1,49,999"],
    ],
    deliverables: [
      "Android app development",
      "iOS app development",
      "Cross-platform mobile solutions",
      "Modern UI/UX design",
      "Secure login and authentication",
      "API integration",
      "Admin panel connectivity",
      "Push notifications",
      "Payment gateway integration",
      "Product and order management",
      "Booking and appointment features",
      "Location and map integration",
      "Database connectivity",
      "Ongoing maintenance and support",
    ],
    audienceTitle: "Made for accessible services",
    audience:
      "We create mobile apps for startups, shops, schools, service providers, online businesses, professionals, and growing companies that want to improve customer engagement and make their services more accessible.",
    choiceTitle:
      "Intuitive app design, secure development, and support after launch.",
    whyChoose: [
      "Responsive and intuitive app design",
      "Secure development",
      "Smooth performance",
      "Scalable architecture",
      "Transparent pricing",
      "Dedicated support after launch",
    ],
    startingPrice:
      "Starting from Rs. 19,999 depending on platform, number of screens, features, integrations, backend requirements, and customization.",
    cta: "Ready to Turn Your Idea Into a Mobile App? Contact Velocity Webtech Solution Today.",
    hidePricingDetails: true,
  },
  {
    id: "custom-software-development",
    path: "/custom-software-development-services/",
    number: "04",
    title: "Custom Software Development",
    eyebrow: "Business automation",
    text: "Build software that fits the way your business actually works instead of forcing your processes into a generic application.",
    icon: MonitorCog,
    tone: "violet",
    storyTitle: "Software shaped around your real workflow.",
    intro:
      "At Velocity Webtech Solution, we develop custom software solutions designed around your business requirements, workflows, users, and long-term goals. From internal management systems to customer-facing applications, we create practical and scalable software that helps reduce manual work, improve accuracy, and streamline daily operations.",
    items: [
      ["Business Software", "Starting at Rs. 49,999"],
      ["CRM / ERP Solution", "Starting at Rs. 79,999"],
      ["School Management Software", "Starting at Rs. 39,999"],
      ["Inventory / Billing Software", "Starting at Rs. 34,999"],
      ["Custom Solution", "Starting at Rs. 69,999"],
    ],
    deliverables: [
      "Business automation systems",
      "CRM and ERP solutions",
      "Inventory management",
      "Billing and POS software",
      "School or institute management systems",
      "Booking and appointment platforms",
      "Workflow management",
      "Reporting dashboards",
      "Role-based access",
      "Database integration",
      "API integration",
      "Payment integration",
      "Notifications",
      "Custom admin panels",
    ],
    audienceTitle: "Tailored for specific processes",
    audience:
      "We build custom solutions for startups, schools, shops, offices, service businesses, growing companies, and organizations that need software tailored to their specific processes.",
    choiceTitle:
      "Requirement-based development, automation-focused features, and room to grow.",
    whyChoose: [
      "Requirement-based development",
      "Clean and scalable architecture",
      "Secure access",
      "Automation-focused features",
      "Easy-to-use interfaces",
      "Future expansion support",
      "Dedicated technical assistance",
    ],
    startingPrice:
      "Pricing depends on the number of modules, user roles, integrations, workflow complexity, reporting requirements, and level of customization.",
    cta: "Need Software Built Around Your Business? Talk to Velocity Webtech Solution and Start Your Custom Software Project Today.",
    hidePricingDetails: true,
  },
  {
    id: "e-commerce-development",
    path: "/e-commerce-development-services/",
    number: "02",
    title: "E-commerce Development",
    eyebrow: "Online selling systems",
    text: "Build a secure, professional, and user-friendly online store that makes it easy for customers to browse products, place orders, and make payments online.",
    icon: ShoppingCart,
    tone: "orange",
    storyTitle: "Online stores designed to sell smoothly.",
    intro:
      "At Velocity Webtech Solution, we develop modern e-commerce websites tailored to your products, customers, and business goals. Whether you are starting a new online store or upgrading an existing business, we create scalable solutions that help you sell more efficiently and manage your store with ease.",
    items: [
      ["Starter Online Store", "Starting at Rs. 29,999"],
      ["Business E-commerce", "Starting at Rs. 49,999"],
      ["Payment Gateway Setup", "Starting at Rs. 9,999"],
      ["Order Management Panel", "Starting at Rs. 19,999"],
      ["Custom Marketplace", "Starting at Rs. 89,999"],
    ],
    deliverables: [
      "Product and category management",
      "Shopping cart",
      "Secure checkout",
      "Payment gateway integration",
      "Customer login",
      "Order management",
      "Inventory tracking",
      "Coupon and discount features",
      "Shipping options",
      "Invoice generation",
      "Mobile-responsive design",
      "Admin dashboard",
      "Search and filtering",
      "WhatsApp/contact integration",
      "Basic SEO setup",
    ],
    audienceTitle: "Built for modern sellers",
    audience:
      "We build e-commerce solutions for retail shops, small businesses, home businesses, startups, wholesalers, service providers, and growing online brands.",
    choiceTitle:
      "A modern storefront, secure checkout, and easy product management.",
    whyChoose: [
      "Modern storefront",
      "Smooth user experience",
      "Secure payment integration",
      "Responsive design",
      "Scalable architecture",
      "Easy product management",
      "Dedicated support after launch",
    ],
    startingPrice:
      "Starting price depends on the number of products, features, payment integrations, shipping requirements, admin functionality, and customization needed.",
    cta: "Ready to Start Selling Online? Build Your E-commerce Store with Velocity Webtech Solution Today.",
    hidePricingDetails: true,
  },
  {
    id: "crm-erp-business-management-systems",
    path: "/crm-erp-business-management-systems-services/",
    number: "05",
    title: "CRM / ERP / Business Management Systems",
    eyebrow: "Business management systems",
    text: "Centralize your leads, customers, operations, billing, reports, and team workflows in one practical business management system.",
    icon: BriefcaseBusiness,
    tone: "cyan",
    storyTitle: "Business systems that keep daily operations organized.",
    intro:
      "Velocity Webtech Solution builds CRM, ERP, and business management systems around your real process. From enquiry tracking and customer records to inventory, billing, reporting, and staff workflows, we create software that helps your team work faster with better visibility.",
    items: [
      ["CRM System", "Custom quote"],
      ["ERP System", "Custom quote"],
      ["Business Dashboard", "Custom quote"],
      ["Inventory and Billing", "Custom quote"],
      ["Workflow Automation", "Custom quote"],
    ],
    deliverables: [
      "Lead and customer management",
      "Staff and role-based access",
      "Inventory and billing workflows",
      "Reports and dashboards",
      "CRM and ERP modules",
      "Task and workflow tracking",
      "Database-backed records",
      "Admin panel controls",
      "API and payment integrations when required",
      "Training and technical support",
    ],
    audienceTitle: "Built for growing operations",
    audience:
      "We build management systems for shops, schools, offices, service providers, startups, teams, and growing companies that need better control over daily business operations.",
    choiceTitle:
      "Organized workflows, secure access, useful reports, and scalable modules.",
    whyChoose: [
      "Requirement-based modules",
      "Clean business workflows",
      "Secure role access",
      "Custom reports",
      "Scalable architecture",
      "Admin-friendly controls",
      "Dedicated support after launch",
    ],
    startingPrice:
      "Pricing depends on modules, user roles, reports, integrations, workflow complexity, and customization required.",
    cta: "Ready to Organize Your Business Operations? Build Your CRM or ERP System with Velocity Webtech Solution Today.",
    hidePricingDetails: true,
  },
  {
    id: "ui-ux-design",
    path: "/ui-ux-design-services-pricing/",
    number: "05",
    title: "UI/UX Design",
    eyebrow: "Modern product design",
    text: "Modern, attractive, and user-focused designs for websites, apps, dashboards, prototypes, and product screens.",
    icon: Layers3,
    tone: "cyan",
    items: [
      ["Landing Page Design", "Starting at Rs. 4,999"],
      ["Website UI Design", "Starting at Rs. 12,999"],
      ["Mobile App UI Design", "Starting at Rs. 19,999"],
      ["Dashboard UI Design", "Starting at Rs. 14,999"],
      ["Clickable Prototype", "Starting at Rs. 9,999"],
    ],
    deliverables: [
      "Clean layout and visual hierarchy",
      "User flows and screen planning",
      "Responsive web and mobile designs",
      "Prototype-ready design direction",
    ],
  },
  {
    id: "api-backend-development",
    path: "/api-backend-development-services/",
    number: "06",
    title: "API & Backend Development",
    eyebrow: "Secure backend systems",
    text: "Build secure, reliable, and scalable backend systems that power your websites, mobile apps, business software, and digital platforms.",
    icon: Server,
    tone: "indigo",
    storyTitle: "Backend architecture built for security and scale.",
    intro:
      "At Velocity Webtech Solution, we develop robust APIs and backend architectures designed to handle your business logic, data, users, integrations, and future growth. Whether you need a new backend from scratch or want to improve an existing system, we focus on performance, security, maintainability, and scalability.",
    items: [
      ["REST API Development", "Starting at Rs. 19,999"],
      ["Database Architecture", "Starting at Rs. 14,999"],
      ["Admin Panel Backend", "Starting at Rs. 24,999"],
      ["Third-party Integration", "Starting at Rs. 9,999"],
      ["Custom Backend System", "Starting at Rs. 49,999"],
    ],
    deliverables: [
      "REST API development",
      "Database design and integration",
      "User authentication and authorization",
      "JWT/OAuth-based security",
      "Admin dashboards",
      "Role-based access control",
      "Payment gateway integration",
      "Third-party API integration",
      "Email and SMS services",
      "File and media handling",
      "Background tasks",
      "Reporting systems",
      "Webhooks",
      "Caching",
      "Logging",
      "Deployment-ready backend architecture",
    ],
    audienceTitle: "Built to power digital platforms",
    audience:
      "We build backend solutions for business websites, mobile applications, e-commerce platforms, CRM/ERP systems, booking platforms, school management systems, dashboards, SaaS products, and custom business applications.",
    choiceTitle:
      "Secure API design, structured databases, and reliable integrations.",
    whyChoose: [
      "Secure API design",
      "Structured databases",
      "Clean backend architecture",
      "Scalable development",
      "Proper authentication",
      "Reliable integrations",
      "Technical support for future enhancements",
    ],
    startingPrice:
      "Pricing depends on API complexity, number of modules, database requirements, authentication methods, integrations, user roles, background processing, reporting, and deployment needs.",
    cta: "Need a Powerful Backend for Your App or Business? Build a Secure and Scalable API Solution with Velocity Webtech Solution.",
    hidePricingDetails: true,
  },
  {
    id: "cloud-deployment-services",
    path: "/cloud-deployment-services/",
    number: "07",
    title: "Cloud & Deployment Services",
    eyebrow: "Launch and support",
    text: "Deploy your websites, applications, and business software with a secure, stable, and properly configured cloud infrastructure designed for reliable day-to-day operation.",
    icon: Cloud,
    tone: "sky",
    storyTitle: "Production deployment built for stability.",
    intro:
      "At Velocity Webtech Solution, we help businesses move their applications from development to a live production environment with proper hosting, domain configuration, server setup, security, performance tuning, and post-launch support. Whether you are launching a new website, API, mobile app backend, or custom software system, we provide deployment solutions based on your technical and business requirements.",
    items: [
      ["Website Maintenance", "Starting at Rs. 2,999 / month"],
      ["POS / Billing Software", "Starting at Rs. 24,999"],
      ["Software Support & Upgrades", "Starting at Rs. 44,999"],
      ["Domain & Hosting Support", "Starting at Rs. 1,499 / year"],
      ["Digital Consultation", "Starting at Rs. 1,999"],
    ],
    deliverables: [
      "Cloud server setup",
      "Linux server configuration",
      "AWS deployment",
      "VPS hosting setup",
      "Nginx configuration",
      "Gunicorn/Uvicorn setup",
      "Docker deployment",
      "Domain and DNS configuration",
      "SSL certificate setup",
      "Database deployment",
      "Environment configuration",
      "Static and media file setup",
      "Reverse proxy configuration",
      "Backups",
      "Basic monitoring",
      "Performance optimization",
      "Production troubleshooting",
    ],
    audienceTitle: "Built for live production systems",
    audience:
      "We support deployment for business websites, Django/FastAPI applications, React/Next.js frontends, mobile app backends, e-commerce platforms, APIs, CRM/ERP systems, and custom business software.",
    choiceTitle:
      "Structured deployment, secure configuration, and reliable launch support.",
    whyChoose: [
      "Structured deployment",
      "Secure server configuration",
      "Proper domain and SSL setup",
      "Optimized application performance",
      "Reliable hosting guidance",
      "Technical support after launch",
    ],
    startingPrice:
      "Pricing depends on cloud provider, server size, deployment complexity, database requirements, number of applications, security configuration, backup needs, monitoring, and ongoing maintenance requirements.",
    cta: "Ready to Take Your Application Live? Deploy Securely and Reliably with Velocity Webtech Solution.",
    hidePricingDetails: true,
  },
  {
    id: "website-software-maintenance",
    path: "/website-software-maintenance-services/",
    number: "08",
    title: "Website & Software Maintenance",
    eyebrow: "Maintenance and support",
    text: "Keep your website or software updated, secure, backed up, and running smoothly with ongoing technical support.",
    icon: Settings,
    tone: "blue",
    storyTitle: "Reliable maintenance for digital systems already in use.",
    intro:
      "Velocity Webtech Solution provides website and software maintenance for businesses that need regular updates, issue fixing, performance checks, backups, and technical support. We help keep your digital platform stable so your business can keep moving.",
    items: [
      ["Website Maintenance", "Custom quote"],
      ["Software Support", "Custom quote"],
      ["Bug Fixes", "Custom quote"],
      ["Security Updates", "Custom quote"],
      ["Feature Upgrades", "Custom quote"],
    ],
    deliverables: [
      "Website content updates",
      "Bug fixing and troubleshooting",
      "Security checks and updates",
      "Backup guidance",
      "Performance review",
      "Software feature updates",
      "Plugin or dependency checks",
      "Server and hosting support",
      "Technical assistance",
    ],
    audienceTitle: "For websites and software that need care",
    audience:
      "We support businesses, schools, shops, service providers, and teams that already have a website or software system and need dependable maintenance.",
    choiceTitle:
      "Fast fixes, practical updates, stable performance, and support when needed.",
    whyChoose: [
      "Regular technical support",
      "Security-focused updates",
      "Performance care",
      "Issue troubleshooting",
      "Clear communication",
      "Flexible maintenance plans",
    ],
    startingPrice:
      "Pricing depends on maintenance frequency, issue complexity, platform type, hosting needs, and requested updates.",
    cta: "Need Reliable Website or Software Support? Contact Velocity Webtech Solution Today.",
    hidePricingDetails: true,
  },
  {
    id: "domain-hosting-assistance",
    path: "/domain-hosting-assistance-services/",
    number: "09",
    title: "Domain/Hosting Assistance",
    eyebrow: "Domain and hosting guidance",
    text: "Get reliable support for setting up the essential online infrastructure your website or application needs to go live smoothly.",
    icon: Database,
    tone: "orange",
    storyTitle: "Domain, hosting, and launch setup without confusion.",
    intro:
      "At Velocity Webtech Solution, we assist businesses, startups, professionals, and organizations with domain registration, hosting setup, DNS configuration, SSL security, business email, and launch preparation. Whether you are creating a new website or moving an existing project to a new hosting provider, we help ensure everything is configured correctly.",
    items: [
      ["Domain Guidance", "Custom quote"],
      ["Hosting Setup", "Custom quote"],
      ["DNS Configuration", "Custom quote"],
      ["SSL Setup", "Custom quote"],
      ["Business Email Setup", "Custom quote"],
    ],
    deliverables: [
      "Domain purchase guidance",
      "Domain connection",
      "DNS record configuration",
      "Nameserver setup",
      "Shared hosting or VPS setup",
      "SSL certificate installation",
      "HTTPS configuration",
      "Business email setup",
      "Website migration",
      "Subdomain creation",
      "Database setup",
      "File deployment",
      "cPanel/hosting panel configuration",
      "Basic troubleshooting",
    ],
    audienceTitle: "Support for common hosting environments",
    audience:
      "We can support websites and applications hosted on shared hosting, VPS servers, cloud platforms, and other common hosting environments, depending on your project requirements.",
    choiceTitle:
      "Clear setup guidance, secure SSL configuration, and final launch support.",
    whyChoose: [
      "Clear setup guidance",
      "Proper domain connectivity",
      "Secure SSL configuration",
      "Reliable hosting assistance",
      "Professional business email setup",
      "Support during final website launch",
    ],
    startingPrice:
      "Pricing depends on domain provider, hosting type, server configuration, email requirements, migration complexity, SSL setup, and the level of technical assistance required.",
    cta: "Need Help Taking Your Website Live? Get Domain, Hosting & Launch Support from Velocity Webtech Solution.",
    hidePricingDetails: true,
  },
  {
    id: "software-training",
    path: "/software-training-services/",
    number: "10",
    title: "Software Training",
    eyebrow: "Training and courses",
    text: "Build practical software skills with guided, hands-on training designed for real-world use in business, administration, and day-to-day digital operations.",
    icon: BookOpenCheck,
    tone: "green",
    storyTitle: "Hands-on software training for real working needs.",
    intro:
      "At Velocity Webtech Solution, we provide practical software training for individuals, students, professionals, business owners, and office staff who want to become more confident using digital tools and business systems. Our training focuses on simple explanations, guided practice, and real working examples.",
    items: [
      ["Admin Panel Training", "Custom quote"],
      ["Software Usage Training", "Custom quote"],
      ["Business Workflow Training", "Custom quote"],
      ["Website Management Training", "Custom quote"],
      ["Custom Course Session", "Custom quote"],
    ],
    deliverables: [
      "Business software usage",
      "Admin panel training",
      "CRM and ERP basics",
      "Billing and POS software",
      "Website content management",
      "Data entry workflows",
      "User and role management",
      "Report generation",
      "Digital documentation",
      "Basic troubleshooting",
      "Workflow automation awareness",
      "Customized training for software developed by us",
    ],
    audienceTitle: "Training for business systems and digital platforms",
    audience:
      "We can also provide training for custom business applications, school management systems, booking systems, inventory software, customer management tools, e-commerce admin panels, and other digital platforms based on the user's requirements.",
    choiceTitle:
      "Step-by-step learning, practical examples, and hands-on support.",
    whyChoose: [
      "Practical guidance",
      "Step-by-step learning",
      "Business-focused examples",
      "Beginner-friendly explanations",
      "Hands-on support",
      "Training tailored to your actual software or workflow",
    ],
    startingPrice:
      "Training fees depend on course duration, number of participants, software complexity, training mode, customization, and the level of post-training support required.",
    cta: "Learn to Use Business Software with Confidence - Get Practical Software Training from Velocity Webtech Solution.",
    hidePricingDetails: true,
  },
];

export const pricingHighlights = [
  {
    title: "Modern Design",
    text: "Attractive, responsive and user-focused designs.",
    icon: BadgeCheck,
  },
  {
    title: "Secure Solutions",
    text: "Robust security, data protection and privacy care.",
    icon: Lock,
  },
  {
    title: "Affordable Pricing",
    text: "Transparent pricing with the right value for money.",
    icon: ShieldCheck,
  },
  {
    title: "Expert Support",
    text: "Dedicated support and guidance at every step.",
    icon: Headphones,
  },
];

export function getPricingSection(id) {
  return pricingSections.find((section) => section.id === id);
}
